### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by Suzie97** [TenderOwl/Frog#10]
@amka, hey there, would you like a new icon for the app? I can design one that follows the human interface guidelines of elementary.

Great app btw, very useful. Cheers!!

**Comment by amka** [comment]
@Suzie97 Sure! I'm so bad at designing icons :) It will be really cool if can make it!

**Comment by Suzie97** [comment]
Cool, I'll make a PR in a soon.

**Comment by Suzie97** [comment]
@amka I made a PR with the icons, lemme know if you like them or you want changes.

**Comment by amka** [comment]
@Suzie97 I'm sorry for such a long delay. Thank you for your submission, it looks great! One thought that bothers me is that I have a few more applications like [Norka](/tenderowl/norka) and [Turtle](/tenderowl/norka) and I like the style of the icons.
May I ask you to try to implement all icons in one style? Just to clarify for the end-user these apps is made by TenderOwl?

**Comment by Suzie97** [comment]
> @Suzie97 I'm sorry for such a long delay. Thank you for your submission, it looks great! One thought that bothers me is that I have a few more applications like [Norka](/tenderowl/norka) and [Turtle](/tenderowl/norka) and I like the style of the icons.
> May I ask you to try to implement all icons in one style? Just to clarify for the end-user these apps is made by TenderOwl?

Do you mean that I do the other icons in the style of Frog? i.e. just using animal faces similar to frog? I can do that.

**Comment by amka** [comment]
@Suzie97 I mean could you create icons for the other apps too?

**Comment by Suzie97** [comment]
> @Suzie97 I mean could you create icons for the other apps too?

yeah sure. You want them in the style of my frog icon right?

**Comment by amka** [comment]
Maybe not so smiling :) Smiling mink looks funny, but I'd prefer thinking of Norka like a tool for a job, not for joy.

**Comment by Suzie97** [comment]
Great. I'll make PRs in the next few weeks. Do you want any changes to the frog icon or are you ready to merge?

**Comment by amka** [comment]
> Great. I'll make PRs in the next few weeks. Do you want any changes to the frog icon or are you ready to merge?

Ah, not sure actually. I like its funny style :) Just wanna it to be in a single idea as the new icons. So if you find a way to make a consistent style - so let it be just as is.

**Comment by amka** [comment]
Closed due to inactivity.

**Comment by devkornev** [comment]
Have you already changed the icon? In my opinion it is not modern. Maybe it changing to something like that?

![Image](https://github.com/user-attachments/assets/1fd26c0b-4ed5-4e17-bbe3-e1355156aeef)
