### ISSUE TITLE
Unable to scroll on the Language list if you have too many languages

### ISSUE THREAD

**Issue by abUwUser** [TenderOwl/Frog#101]
If you have too many languages downloaded, some languages may be unselectable if you don't have the proper screen size
![image](https://user-images.githubusercontent.com/27961224/235313415-e2af091f-fddb-4b8f-9e86-5aa9d15c8349.png)
Note that this does not happen in the "Second Language" dialogue due to it having a proper scrollbar
![image](https://user-images.githubusercontent.com/27961224/235313474-df788038-6048-48d6-a597-8330ccfb0621.png)

**Comment by amka** [comment]
I decided to make it a little bit differently. Seems viable for me. @abUwUser what do you say?
![](https://github.com/TenderOwl/Frog/assets/519146/089f2166-1bb0-49fe-918c-d5a7151ae475)

**Comment by abUwUser** [comment]
seems good! tho i guess it could also be neat to list all available languages and if the language selected isn't available it does automatic download, like what's done at google translate

**Comment by amka** [comment]
Yeah, good idea!

**Comment by amka** [comment]
Close this issue. The new functionality will be added in a new issue.
