### ISSUE TITLE
[Bug] local installation fails to launch

### ISSUE THREAD

**Issue by werdahias** [TenderOwl/Frog#108]
OS: Debian Bookworm
 I cloned the latest master and built and installed it. lauch frog gets's me the following error:

```
/usr/local/bin/frog 
Traceback (most recent call last):
  File "/usr/local/bin/frog", line 59, in <module>
    from frog import main
ModuleNotFoundError: No module named 'frog'

```

Another thing I noticed: meson references release 1.3.0 but GH has only 1.2.0.
Furthermore, meson emits a warning about outdated features:
```

Project version: 1.3.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
meson.build:16: WARNING: Project targets '>= 0.50.0' but uses feature deprecated since '0.48.0': module python3.
```

**Comment by iam-TJ** [comment]
The failure is due to a Debian-specific packaging layout, described in:

https://github.com/mesonbuild/meson/issues/8739

The deprecation warning is due to using the old meson "python3" module rather than its replacement, "python". I've made a PR in #115

**Comment by amka** [comment]
Since it is a Debian-specific problem I close this issue.
