### ISSUE TITLE
Hide Window on Clicking Snip Button

### ISSUE THREAD

**Issue by candiedoperation** [TenderOwl/Frog#11]
@amka, On clicking the **snip button**, using `GtkWindow.Hide()` on the main window would help taking screenshots easily instead of moving Frog's Window all over the desktop

_Originally posted by @candiedoperation in https://github.com/TenderOwl/Frog/discussions/7#discussioncomment-1274794_

**Comment by hezral** [comment]
Came here to suggest this as well. 

What i did for [Clips](https://github.com/hezral/clips) was to check if it is the active app using xlib and connect the "state-flags-changed" signal for the main window to trigger the check. Would be interested if there is a better way. 

I had this app idea too but was focused on building Clips, i like this app 😄

**Comment by amka** [comment]
Well, I've done this by doing capture in an async way. Just call the `capture()` method and then `.hide()`. Use `.present()` on callback of the `capture()` method.

**Comment by seltzered** [comment]
Do others notice the window actually hide? I've been using Frog for a while (currently on 1.5.2) and not sure I've ever seen the window actually hide away when clicking the 'Take a Screenshot' button.
