### ISSUE TITLE
Text is not extracted

### ISSUE THREAD

**Issue by atishdhu** [TenderOwl/Frog#12]
The text does not appear to be extracted after taking the screenshot. Its only saving the image. The text also is not saved in the clipboard. Am i using it wrong?

**Comment by atishdhu** [comment]
I rebuilt the app using builder and when i run it within builder it works well.

But when i built the flatpak and installed the app using the flatpak it does not work anymore. I think the problem comes from here.

**Comment by amka** [comment]
Hey @atishdhu! Did you download the language file you need to extract? the Frog doesn't mean to save images after work, only for temporary needs. So in your case, it looks like something goes wrong.

**Comment by atishdhu** [comment]
The app works now. I reinstalled it from the store but instead opened it from the terminal once using
```
flatpak run com.github.tenderowl.frog
```
Now it works fine. This seems to be an issue with flatpak itself. I will continue testing it and get back.

Thanks!

**Comment by amka** [comment]
Sounds good! I think we can close this issue.
