### ISSUE TITLE
Quick snip and copy to clipboard

### ISSUE THREAD

**Issue by zilpe** [TenderOwl/Frog#127]
Hello,

Great work on the app!

As someone who has been using [Text Grab](https://github.com/TheJoeFin/Text-Grab) on Windows for ages, a really useful feature would be to have a shortcut to directly open the 'snipping tool' and once selected, copy the recognised text to the clipboard (rather than having to go through many menus every time).

This is  linked to #81 too. Thanks again!

**Comment by amka** [comment]
@zilpe  Thank you for your kind words! I've done some research on this idea and unfortunately haven't found a good solution yet. So the issue is still open and I plan to implement it eventually.
