### ISSUE TITLE
Flathub version uses GNOME 41

### ISSUE THREAD

**Issue by MANICX100** [TenderOwl/Frog#137]
If I install via appcentre flatpak GNOME 41 which is now depreciated ISN'T needed if I install via flathub it is.

**Comment by amka** [comment]
@MANICX100 I'm not sure I get it. The Flathub version is built on top of GNOME SDK 44. But if you're talking about elementary AppCenter, I must check it.

**Comment by MANICX100** [comment]
> @MANICX100 I'm not sure I get it. The Flathub version is built on top of GNOME SDK 44. But if you're talking about elementary AppCenter, I must check it.

No I was getting the warning when updating from flathub. But can't replicate it now so will close.
