### ISSUE TITLE
Can't download the language packs.

### ISSUE THREAD

**Issue by alimalrazi95** [TenderOwl/Frog#14]
![image](https://user-images.githubusercontent.com/74136531/133994919-ffe40465-e27b-4f40-ba23-2b4ceefa5e38.png)

**Comment by amka** [comment]
@alimalrazi95  Looks like the process is started. Did you receive an in-app notification a bit later? Because it depends on your internet connection speed.
At the moment the app has no debug mode but surely I have to add it in the next versions.

**Comment by alimalrazi95** [comment]
The process was running for some time. I've started checking this morning again. The app has been running over 2 hours and still hasn't downloaded anything. Meanwhile, I'm browsing stuffs, watching youtube just fine.

**Comment by zedtux** [comment]
Same issue here.

Also clicking the "OK" button, then coming back shows a square, like a checkbox at the right hand side of the spinner.

**Comment by amka** [comment]
The updated version will be available soon in the AppCenter.

**Comment by zedtux** [comment]
Thank you @amka, I'll give an update as soon as I see the update.

**Comment by zedtux** [comment]
I confirm the download issue is fixed. After the download has succeeded, a flash message appears, but the spinner remain which is confusing.

Anyways, thank you!
