### ISSUE TITLE
Make it possible to 'Select an area' as the default while making a screenshot

### ISSUE THREAD

**Issue by joenepraat** [TenderOwl/Frog#141]
My use case is almost always to make a screenshot of an image or part of the image. I always use the 'Select an area' in the screenshot dialog. When I need to do this multiple times, it's not user friendly to always change the option back from 'The whole screen' to 'Select an area'.

Thanks for considering this.

![image](https://github.com/TenderOwl/Frog/assets/41594439/fb67c155-2185-4a95-b118-7e4f43c8e2fa)![image](https://github.com/TenderOwl/Frog/assets/41594439/9aac2a86-207a-4076-b04e-976b2d8b90a7)

**Comment by amka** [comment]
Duplicates #81
