### ISSUE TITLE
Append preference for the screenshot saving path

### ISSUE THREAD

**Issue by signdo** [TenderOwl/Frog#146]
Maybe you can add whether to save screenshots by default and where screenshots are saved.

**Comment by amka** [comment]
I prefer considering applications like Install & Run without requiring extra configurations. I assume it could be an option inside the Preferences dialog, yet let me know why this is a good option for you.

**Comment by signdo** [comment]
I love and use this program a lot. But I don't want to save the screenshot, it doesn't matter.
The screenshots of this program will be saved in the root directory of the Pictures folder, which will be very distressing for people who like to organize folders. I think you can add a directory to the Pictures folder dedicated to the screenshots of this program.

**Comment by amka** [comment]
Ah, I see. This issue is caused by the underlying usage of portals so thank you for mentioning it. I think I have an idea of how to make it invisible to a user and remove old screenshots silently.
