### ISSUE TITLE
Remember the last choice

### ISSUE THREAD

**Issue by azzamsa** [TenderOwl/Frog#147]
Hi.

It will be faster to take new screenshots if Frog remembers the last choice of "Take screenshot". We don't need to choose "select area to grab" every time.
 
 Thanks for Frog! 🏅

**Comment by amka** [comment]
@azzamsa Hey! Unfortunately, the root of this behaviour comes from the underlying portals technology which is a preferred way to take a screenshot from a flatpak sandbox. I'm working on a completely new grab feature yet it requires a lot of research.

I'll close this issue in favor of #81
