### ISSUE TITLE
It isn't clear why "Grab the area" button is greyed out on the first start

### ISSUE THREAD

**Issue by delight-aug** [TenderOwl/Frog#15]
~~The "Grab the area" button is greyed out. I have no idea why and how to overcome this.~~ So, the "Grab the area" button is greyed out by default since there is no language to scan for. But it really isn't clear by default, I even went to open issue :-) I suggest shipping English with the app.

![Screenshot from 2021-09-25 02 15 34](https://user-images.githubusercontent.com/51861383/134748506-859f53d5-247e-43e7-876c-6cc041a68eeb.png)

**Comment by amka** [comment]
That is absolutely normal. You have no languages downloaded so Frog has no options to choose and extract. You have to "configure languages" to proceed. 

Maybe I need to clarify this at the first launch.

**Comment by delight-aug** [comment]
Yep, I just realized it and edited the comment. Thanks for quick response, please reread the issue description.

**Comment by Fuseteam** [comment]
definitely not clear, in my case i also had to restart the app after configuring languages

**Comment by amka** [comment]
English model will be distributed with the app.
