### ISSUE TITLE
After downloading the first language, the language chooser defaults to an empty value

### ISSUE THREAD

**Issue by delight-aug** [TenderOwl/Frog#16]
After downloading the first language, the language chooser defaults to an empty value. To reproduce, delete all languages (or have a fresh install) and download a language.

![Screenshot from 2021-09-25 02 25 12](https://user-images.githubusercontent.com/51861383/134749022-b6d433ed-5b01-4203-ac0d-a6b11defe828.png)

**Comment by amka** [comment]
Same as the previous one. It looks like the app is working fine but I have to clarify it for the user.

**Comment by delight-aug** [comment]
I think it's better to automatically choose the first downloaded language because having it unchosen doesn't serve any purpose, and you can't unset it again if there are languages installed.
