### ISSUE TITLE
Not working on other OS

### ISSUE THREAD

**Issue by Radical4ever** [TenderOwl/Frog#19]
well, the issue is that i cant use it on gnome, (im using fedora 35) and after i downloaded the languages that i need and then press the "grab area" button it just reset the app, i tried changing some permissions but that didnt work.

**Comment by amka** [comment]
@Radical4ever what os do you use? 
Frog is not supported on the other OS as it stands from the description and is not distributed to the other OS. How did you install it?

**Comment by Radical4ever** [comment]
From the flatpakref, since elementary moved to flatpak they have their own repo, and you can download the flatpak installer from the appcenter page.

**Comment by Radical4ever** [comment]
> From the flatpakref, since elementary moved to flatpak they have their own repo, and you can download the flatpak installer from the appcenter page.

Uses the `io.Elementary.Platform` to run Appcenter apps

**Comment by amka** [comment]
Probably the way it fails is because of missed GNOME Screenshot tool, which is installed in every elementary OS installation and D-Bus interface of what is used to make a screenshot. I'll make some research but it requires a few days. 
In any case, I'll add clarification messages to the app to let users know if something goes wrong. Thank you!

**Comment by Radical4ever** [comment]
> Probably the way it fails is because of missed GNOME Screenshot tool, which is installed in every elementary OS installation and D-Bus interface of what is used to make a screenshot. I'll make some research but it requires a few days. In any case, I'll add clarification messages to the app to let users know if something goes wrong. Thank you!

You're welcome!!. i hope you find a solution or a how to. im going to see if i can solve it too and i post it here!

**Comment by abhitrueprogrammer** [comment]
I was having the same problem, and launched the app using terminal. The following errors were that I got
```
Gtk-Message: 10:29:59.157: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:29:59.157: Failed to load module "pk-gtk-module"
Cache downloaded codes, ['eng']
ERROR: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: SelectArea is not allowed (9)
```
The last ERROR: g-dbus-error-quark: GD.... occurs when I click the grab area button. 

Also using Fedora 35

**Comment by marcelovbcfilho** [comment]
Don't know if this is useful, *but* found an issue saying that this probably is due to Gnome 41 and aparently is fixed in the maix Gnome source.
https://githubmemory.com/repo/SeaDve/Kooha/issues/109

**Comment by amka** [comment]
@marcelovbcfilho seems to be true. I'll add a more meaningful error messages but probably can't fix this issue.

**Comment by 13hannes11** [comment]
Could this be related to wayland?

**Comment by Radical4ever** [comment]
> Could this be related to wayland?

Nop, i tried using it on wayland and happens the same thing.

**Comment by amka** [comment]
Please check via the latest commit, it contains some logs and notifications to describe its condition. Maybe it will give you an understanding of what's going on.

**Comment by amka** [comment]
Soon I'll release new version to Flathub. It won't require access to the home folder and also use [libportal](https://libportal.org) to take screenshots. Hope it helps.

**Comment by amka** [comment]
Closed due to inactivity.
