### ISSUE TITLE
How to uninstall frog?

### ISSUE THREAD

**Issue by matefs** [TenderOwl/Frog#210]
How to uninstall frog?

i'm on ubuntu 
OS: Ubuntu 22.04.4 LTS x86_64

**Comment by soumyaDghosh** [comment]
You installed it using `snap`?

**Comment by matefs** [comment]
- I installed it from ubuntu store.
- Trying to remove with `apt remove frog` says that is already uninstalled : ( 
![image](https://github.com/user-attachments/assets/6a393b0f-c917-4a44-85c7-15b34792f601)
- But if i search on gnome launcher it keep showing 
![image](https://github.com/user-attachments/assets/b4487113-1336-41bc-a94e-4a44d6774459)

**Comment by soumyaDghosh** [comment]
What does this shows

`which frog`

**Comment by matefs** [comment]
[ SOLVED ]
```bash
~ …
➜ sudo snap remove frog              
frog removed

```
![image](https://github.com/user-attachments/assets/5a370965-0751-4e02-ada6-9bbcedbf3e17)
