### ISSUE TITLE
KeyError: 'XDG_DATA_HOME'

### ISSUE THREAD

**Issue by yochananmarqos** [TenderOwl/Frog#22]
I just built Frog from source (tried both 0.1.7 & from latest commit) on Manjaro GNOME. Yes, I'm aware it's not meant for anything other than Elementary. 

It appears it's looking for `~/.local/share/tessdata/` and should create it if it doesn't exist. However...

```
❯ frog
Traceback (most recent call last):
  File "/usr/bin/frog", line 51, in <module>
    from frog import main
  File "/usr/lib/python3.9/site-packages/frog/main.py", line 37, in <module>
    from .settings import Settings
  File "/usr/lib/python3.9/site-packages/frog/settings.py", line 32, in <module>
    from frog.config import APP_ID
  File "/usr/lib/python3.9/site-packages/frog/config.py", line 33, in <module>
    if not os.path.exists(os.path.join(os.environ['XDG_DATA_HOME'], 'tessdata')):
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_DATA_HOME'
```

**Comment by amka** [comment]
The error is quite descriptive itself: your system doesn't provide the required environment variable - `XDG_DATA_HOME`.
The Frog implies having access to this var because of https://docs.flatpak.org/es/latest/conventions.html#xdg-base-directories.

You could try to put it in your profile to make Frog work properly.

**Comment by yochananmarqos** [comment]
Ah, turns out [user directory variables ](https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories)are not set by default. I added them to my `~/.profile`.

```
❯ echo $XDG_DATA_HOME
/home/yochanan/.local/share
```

However, I'm receiving the exact same error.

**Comment by yochananmarqos** [comment]
If I run `XDG_DATA_HOME="$HOME/.local/share/" frog`, I'm getting somewhere. However, it can't find `eng.traineddata` because it's looking in `/app/share/appdata/` instead of `/usr/share/appdata/`. It seems to be hardcoded in `language_manager.py`.

```
Traceback (most recent call last):
  File "/usr/bin/frog", line 52, in <module>
    sys.exit(main.main(VERSION))
  File "/usr/lib/python3.9/site-packages/frog/main.py", line 121, in main
    app = Application()
  File "/usr/lib/python3.9/site-packages/frog/main.py", line 61, in __init__
    language_manager.init_tessdata()
  File "/usr/lib/python3.9/site-packages/frog/language_manager.py", line 163, in init_tessdata
    copyfile(source_path, dest_path)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/app/share/appdata/eng.traineddata'
```

**Comment by amka** [comment]
Soon I'll release new version to Flathub. It won't require access to the home folder and also use [libportal](https://libportal.org) to take screenshots. I'm not the user of Manjaro but hope it helps.

**Comment by yochananmarqos** [comment]
Sounds good. :+1: 

Technically, my issue has nothing to do with Manjaro or any other distribution. The point is, it isn't currently compatible with installing from source code using sane specifications and guidelines.

**Comment by amka** [comment]
Ah, that's true. I designed it specifically for elementary OS and have no thought on support the other distros. But the time has come and the Frog is moving towards any compatible (I mean with Screenshot Portal) distro.

**Comment by yochananmarqos** [comment]
It's working now with the latest commit with a couple workarounds. Here's my [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/blob/master/elementary-frog/PKGBUILD).

**Comment by yochananmarqos** [comment]
FYI, I've added it to the AUR as [`frog-ocr`](https://aur.archlinux.org/packages/frog-ocr) and let users know they need to set the `XDG_DATA_HOME` variable.

**Comment by yochananmarqos** [comment]
What do you mean? If `~/.local/share/tessdata/eng.traineddata` does not exist it's created on launch. Without the variable set, it can't find where to create it.
