### ISSUE TITLE
The Math / equation detection module does not finish downloading

### ISSUE THREAD

**Issue by HariSK20** [TenderOwl/Frog#27]
**Errors** 
![frog_error_equModule](https://user-images.githubusercontent.com/56635847/152648940-f937cee6-5578-40ca-8e35-91186585ce06.png)

**Cause** 
cannot find the required model

On inspection, I found that it fails because the tesseract-ocr trained models at [tessdata_best](https://github.com/tesseract-ocr/tessdata_best/) does not have the required ‘equ’ model. 
But as listed on the [Data files section of Tesseract docs](https://tesseract-ocr.github.io/tessdoc/Data-Files.html),  The ‘equ' module is available at  [tessdata](https://github.com/tesseract-ocr/tessdata/).

**Comment by HariSK20** [comment]
May I try to implement a solution?  
If any of the links to [tessdata_best](https://github.com/tesseract-ocr/tessdata_best) doesn't exist, then it checks [tessdata](https://github.com/tesseract-ocr/tessdata/) and if found, downloads it.

**Comment by amka** [comment]
@HariSK20 I would be appreciated :)

**Comment by HariSK20** [comment]
Thank You for giving me this opportunity to contribute!
