### ISSUE TITLE
 Frog failed to initialize screenshots service on Parrot OS 

### ISSUE THREAD

**Issue by AlexWarGuate** [TenderOwl/Frog#31]
Hello, I'm trying to use Frog, the text extractor, in the latest version of Parrot Os, but I can't get it to start the screenshot service, what could I do, what other alternative could I use, I really like this application a lot but I can't make it run.

I just love your APP

thanks for your help

Best regards

![Problema Frog](https://user-images.githubusercontent.com/101735596/159130450-1cf54b2a-3860-477a-8a55-4abfd87b00e5.png)

**Comment by amka** [comment]
Soon I'll release new version to Flathub. It won't require access to the home folder and also use [libportal](https://libportal.org) to take screenshots. I'm not the user of ParrotOS, but hope it helps.

**Comment by AlexWarGuate** [comment]
Sounds great, I'll keep an eye out, thanks for the great work 

Best regards

**Comment by amka** [comment]
@AlexWarGuate pls check against [Flathub version](https://flathub.org/apps/details/com.github.tenderowl.frog)

**Comment by AlexWarGuate** [comment]
@amka thank you very much, sorry for the delay, it was due to a medical condition, I already updated to the new version, when I try to capture this window appears, basically it asks if I want to capture the full screen, or a crop and the delay time, then it just close it up.

![image](https://user-images.githubusercontent.com/101735596/160928948-7a61b732-e45b-45bd-8990-945e5622cb85.png)
 

![image](https://user-images.githubusercontent.com/101735596/160928428-a35a11af-c0bc-4a3c-9834-02f480be1c50.png)


Running Frog from the terminal it shows me this message 

![image](https://user-images.githubusercontent.com/101735596/160929488-2dc8b7a2-44cf-4e59-b1a7-ce8a7a0d3810.png)

Thanks for the effort, I love this app, it's my favorite app on Elementary OS
