### ISSUE TITLE
UI translation to other languages

### ISSUE THREAD

**Issue by not-a-dev-stein** [TenderOwl/Frog#33]
I imagine it would take some work to set everything needed to translate the app to other languages, but now that the portal integration is done it would be nice to be able to help translate it.

A Weblate instance, for example, would help a lot to make the process easier for everyone to contribute.

**Comment by amka** [comment]
Sure, that's a good idea!

**Comment by amka** [comment]
Hey @not-a-dev-stein! https://hosted.weblate.org/projects/frog/ is waiting for approval and once it will be done you'be able to add new languages :)
