### ISSUE TITLE
LibHandy and Granite are included in the elementary Platform

### ISSUE THREAD

**Issue by cassidyjames** [TenderOwl/Frog#4]
You shouldn't need to include these manually here, they're included in the platform.

https://github.com/TenderOwl/Frog/blob/f7e70b39e3df9e733839744c61253014a78d78ba/flatpak/com.github.tenderowl.frog.json#L30-L55

**Comment by amka** [comment]
I knew it! Done.

**Comment by cassidyjames** [comment]
@amka don't forget to make a new release so we can re-review this. :smile:

**Comment by amka** [comment]
@cassidyjames do I need to discard https://github.com/elementary/appcenter-reviews/pull/82 and create a new one?

**Comment by btkostner** [comment]
Nope, we can just update that PR :confetti_ball:
