### ISSUE TITLE
GNOME Circle

### ISSUE THREAD

**Issue by sonnyp** [TenderOwl/Frog#49]
Hi there – very cool app - thanks!

Would you consider joining GNOME Circle?

https://circle.gnome.org/

FYI – reviewer might ask for some changes to match GNOME a big closer, but nothing too drastic as the app is really close already.

Cheers

**Comment by amka** [comment]
Hey! I'd love to but I need to design new icon. And that is the hardest task for me 🤣

**Comment by musiclover382** [comment]
What’s the problem with the current frog?

**Comment by bertob** [comment]
Feel free to apply regardless, things like icon style can be discussed during review :)

**Comment by amka** [comment]
@bertob  I did!
