### ISSUE TITLE
The app won't launch unless I choose to "Launch using discete graphics card"

### ISSUE THREAD

**Issue by vescovaccio** [TenderOwl/Frog#53]
I was using Frog on the same machine with an Nvidia card on Ubuntu 21.10 and everything worked fine. I updated to Ubuntu 22.04 and now I have to manually select "Launch using discete graphics card" to be able to use Frog. Launching via the command line gives me this error message:

->
libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: DRI2: could not open /dev/dri/card0 (No such file or directory)
libGL error: MESA-LOADER: failed to retrieve device information
Cache downloaded codes: ['eng', 'ita']
No provider of glGetShaderiv found.  Requires one of:
    Desktop OpenGL 2.0
    OpenGL ES 2.0
->

I believe I have OpenGL ES 3.2 installed not OpenGL ES 2.0.

**Comment by amka** [comment]
This looks weird. You could try to set the flag `PrefersNonDefaultGPU=true` to the .desktop file and check if it runs OK.

**Comment by vescovaccio** [comment]
Thanks Amka!

There were three desktop files, two under /var/lib/flatpak/app/com.github.tenderowl.frog/x86_64/stable/ ..., and one under /var/lib/flatpak/exports/share/applications/. 

I added "PrefersNonDefaultGPU=true" to only the latter, and now it works as an ordinary user might expected. Frog just starts without needing to select "Launch with discrete graphics".

With "PrefersNonDefaultGPU=true", I imagine it is now using my Nvidia GPU, as Ubuntu is doing something like "Don't use the Nvidia GPU unless specifically asked". So, with this flag, it is using Nvidia, and without it, it is using Intel graphics.

Which leads me to the question:

Does Frog not work on Intel graphics alone? Or, let's say, on my Intel graphics? I thought Intel graphics would be enough to run Frog. Or maybe it is my specific Intel chip ...

Let me give some more info on my set up:

Intel® Core™ i7-10510U CPU @ 1.80GHz × 8 
Mesa Intel® UHD Graphics (CML GT2) / Mesa Intel® UHD Graphics (CML GT2)

NVIDIA GeForce MX250 (GP108BM)
nvidia-driver-510
Nvidia settings: "On-Demand" (i.e. not "Performance Mode")

**Comment by amka** [comment]
Actually, it doesn't rely on a graphics card at all. All the logic inside works pretty well on a CPU. 

The fact the app worked before the Ubuntu upgrade leads me to the idea your issue comes from the drivers, Wayland and Gtk4, and not the app itself.

**Comment by vescovaccio** [comment]
Thanks. I was pretty sure that Frog didn't need to use the GPU. But the issue is strange. Even though it may not use it, it seems to want it enabled. It's certainly not a Wayland issue, since I'm still using X. The Nvidia driver is the exact same as I used before the upgrade of Ubuntu, so it's probably not that either. It may, therefore, more likely be a Gtk4 issue ...

**Comment by amka** [comment]
Take a look here https://askubuntu.com/questions/1371650/configuring-opengl-es-to-work-with-i915-driver
Maybe it will help.

**Comment by vescovaccio** [comment]
I did some updates - I think there was a kernel update in there - and I tried deleting the added line "PrefersNonDefaultGPU=true" from the .desktop file - and now it seems to work fine (i.e. without having to launch with discrete graphics). I don't know how, but this issue seems to be resolved for me, for now. I guess the issue can be closed. Many thanks, Frog is a wonderful little program!
