### ISSUE TITLE
Error starting frog on Fedora 36 - No provider of glGetShaderiv found.

### ISSUE THREAD

**Issue by brpaz** [TenderOwl/Frog#56]
Hello. I installed From from Flatpak in a recently updated Fedora 36 install, but when I start the application, it crashes with the following error:

```
libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: DRI2: could not open /dev/dri/card0 (No such file or directory)
libGL error: MESA-LOADER: failed to retrieve device information
Cache downloaded codes: ['eng']
No provider of glGetShaderiv found.  Requires one of:
    Desktop OpenGL 2.0
    OpenGL ES 2.0
```

I found out some Reddit thread of a similar problem regarding GTK4 apps and they said to run with `GSK_RENDERER=cairo` environment variable and it works.

This error only apps in Frog and not other GTK4 apps.

I seem to have OpenGL installed:

```
❯ glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
``

**Comment by amka** [comment]
I'm on Fedora 36 from beta and still have no issues like these. Do you use an Intel card? Please look at #53.

**Comment by brpaz** [comment]
Yes, I have an Intel card.
I found a user with exactly the same problem on Reddit - https://www.reddit.com/r/archlinux/comments/v2qrjf/mesaloader_problem_to_run_flatpak_app/  and the solution worked.

I needed to give `dri` permission to the Flatpak for it to work.

**Comment by amka** [comment]
I'll add it to the next release. But for now, I'm glad you found a solution.
