### ISSUE TITLE
Does not run on MX Linux

### ISSUE THREAD

**Issue by onsosb** [TenderOwl/Frog#60]
Hi,
Your program is useful and easy to use.  I congratulate you for creating it.  Is is really time saver for me.  I used it on popOS with no issue.
But now I am supposed to work on MX Linux and unfortunately it won't work there.  Neither the one in their MX repository nor the one I created using builder nor the one from Elementary  OS.
Program starts fine
When you click on Take snapshot it ends.  I do not see any error messages or any clue as why it happens and where...
Looking forward to your comments and possible fix.
Thanks.
Bid
PS: here is my platform info:
**Linux mx 5.16.0-5mx-amd64 #1 SMP PREEMPT Debian 5.16.14-1~mx21+1 (2022-03-22) x86_64 GNU/Linux**

**Comment by amka** [comment]
Hey @onsosb ! I will check it against MX Linux 21.1. x64 XFCE edition and come back to you in a few days.

**Comment by onsosb** [comment]
Thanks a lot and dorry for belated response.
Cheers

**Comment by amka** [comment]
Hey @onsosb ! Unfortunately Frog uses Screenshot portal to take a screenshot but MX Linux doesn't support this. Due to Flatpak security policy I'm not sure I want to implement screenshot without Portals. Thus I have no solution for  you yet. 😞

**Comment by onsosb** [comment]
Thanks for looking at the issue. At least now I know what is the show stopper.  I sincerely do appreciate you wonderful work, will certainly follow its progress.
Cheers
