### ISSUE TITLE
Flatpak locale not working/load (French)

### ISSUE THREAD

**Issue by RobOT05442309** [TenderOwl/Frog#61]
Hello,

First of all, thanks for your work on this amazing app!

I saw that you've made GUI translation available for several languages including French, but after installing and setup the app, I still have english language display on button into the GUI, I've digging a bit before posting an issue but so far I'm out of luck to get things work.

- System: Fedora 36
- Flatpak version: 1.12.7
- System language : French

#### Installation (system)

Command used for install:

```sh
> flatpak install flathub com.github.tenderowl.frog
```

I have also forced the installation of locale (even if they where still installed by default)

```sh
> flatpak install flathub com.github.tenderowl.frog.Locale
```

Try a flatpak update after install (in case something missing)

```sh
> flatpak update
```

#### Configuration (system)

This is some output of my system configuration:

```sh
> flatpak config --system --list

languages: fr;en (default: fr)
extra-languages: *unset*
```

```sh
> flatpak config --user --list

languages: fr;en (default: fr)
extra-languages: *unset*
```

#### Informations (flatpak)

```sh
> flatpak info com.github.tenderowl.frog

Frog - Extract text from anywhere, even QR code

ID: com.github.tenderowl.frog
Ref: app/com.github.tenderowl.frog/x86_64/stable
Arch: x86_64
Branch: stable
Version: 1.1.1
License: MIT
Origin: flathub
Collection: org.flathub.Stable
Installation: system
Installed: 26,4 MB
Runtime: org.gnome.Platform/x86_64/42
Sdk: org.gnome.Sdk/x86_64/42

Commit: b14bfaf3fcdb7dd3d6e9f4aacff5d0e459ef30498f661edc8a354f77b511d726
Parent: 33449479830dd70e38cdbbf257aba67bb3511cf838aebac7cf0f1f41cabacea6
Subject: Update to 1.1.2 (9910ebcd)
Date: 2022-06-07 10:51:01 +0000
```

```sh
> flatpak info com.github.tenderowl.frog.Locale

ID: com.github.tenderowl.frog.Locale
Ref: runtime/com.github.tenderowl.frog.Locale/x86_64/stable
Arch: x86_64
Branch: stable
Origin: flathub
Collection: org.flathub.Stable
Installation: system
Installed: 512 bytes

Commit: dac13a117167ba47667cf6e6a0f8f8c7127b2112cfcfd0ea3068879aeb85cb94
Parent: 23eea8c74d1ed72b4d1b3d1cfd9677896cd11616601b97075d16b29cf1ce5de7
Subject: Update to 1.1.2 (9910ebcd)
Date: 2022-06-07 10:51:06 +0000
Subdirectories: /en,/fr
```

#### Locales (testing)

So far I've try to dig a bit and it seems that translation file are not present in the flatpak build (I don't know if this is relevant):

```sh
> flatpak run --command=ls com.github.tenderowl.frog /app/share/locale/

ja  ru
```

```sh
> ls -la /var/lib/flatpak/app/com.github.tenderowl.frog/current/active/files/share/locale/

total 8
drwxr-xr-x.  2 root root 4096  1 janv.  1970 .
drwxr-xr-x. 13 root root 4096  1 janv.  1970 ..
lrwxrwxrwx.  1 root root   38  9 juin  11:37 ja -> ../../share/runtime/locale/ja/share/ja
lrwxrwxrwx.  1 root root   38  9 juin  11:37 ru -> ../../share/runtime/locale/ru/share/ru
```

```sh
> ls -la /var/lib/flatpak/app/com.github.tenderowl.frog/current/active/files/share/runtime/locale/

total 16
drwxr-xr-x. 4 root root 4096  1 janv.  1970 .
drwxr-xr-x. 3 root root 4096  1 janv.  1970 ..
drwxr-xr-x. 2 root root 4096  1 janv.  1970 ja
drwxr-xr-x. 2 root root 4096  1 janv.  1970 ru
```

Even running the application and forcing environment doesn't to work to get French language:

```sh
> flatpak run --env=LC_MESSAGES=fr_FR.UTF-8 com.github.tenderowl.frog
```

#### Links

I've find some links related to that kind of issue, one that might be relevant is:

- https://github.com/flathub/org.gnome.Rhythmbox3/issues/53

I'm missing some knowledge about how flatpak might interact between runtime and app but I don't understand why it's not working at all for me to get French language in GUI.

Other flatpak app are working with French language so I think it might be related to how Frog handle things, I don't know if anyone have the same issue for other language, I haven't found any issue related on this repository (open or closed).

Thanks for your feedback on this matter when you'll get time, have a nice day.

**Comment by amka** [comment]
Thank you @RobOT05442309! I'll check and come back in a few days.

**Comment by flipflop97** [comment]
The same with Dutch, the app just displays in English. So it's probably a general localisation issue.

**Comment by amka** [comment]
Ah, I found the issue. We're gonna need to update translation files and it will work again.

**Comment by RobOT05442309** [comment]
Nice! Thanks you for the feedback and the quick resolution!

**Comment by amka** [comment]
@RobOT05442309 @flipflop97 please check against version 1.1.3

**Comment by RobOT05442309** [comment]
Sill the same with version 1.1.3, every command listed on the report get the exact sames result, only "ru" and "ja" are available, do you need us to do something else to give you a feedback on this ?

Thanks to take time to investigate!

**Comment by flipflop97** [comment]
[Ah, I think I see why 😅](https://github.com/TenderOwl/Frog/blob/master/po/LINGUAS)
