### ISSUE TITLE
Cannot paste screenshots using GNOME's screenshot software

### ISSUE THREAD

**Issue by indicozy** [TenderOwl/Frog#74]
First of all, thanks Andrey Maksimov for this product! I like it much and use it often.

However, it lacks or it is buggy to use it more intuitively. I usually take a screenshot using GNOME 42's screenshot software (the one that pops up when you press PrintScreen). When I copy my screenshot to clipboard and send it to frog via Ctrl+V, it does nothing.

For instance, in [Obfuscate](https://flathub.org/apps/details/com.belmoussaoui.Obfuscate) I can send the image via Ctrl+V and it is really intuitive. I want that feature to be also in Frog.

OS: OpenSUSE Tumbleweed, v20220905;
DE: GNOME 42.4 on Wayland
Frog: v1.2.0 via Flatpak, from Flathub

Please reply if you need more info

**Comment by BarbzYHOOL** [comment]
+1

**Comment by hyuri** [comment]
+1
Came here to suggest support for pasting from clipboard.

**Comment by amka** [comment]
I think it should be something like...

<video src=https://github.com/TenderOwl/Frog/assets/519146/adb6b49c-fc0b-45cc-a791-0f728d548fd1 />
