### ISSUE TITLE
Flatpak install failed

### ISSUE THREAD

**Issue by rayrrr** [TenderOwl/Frog#78]
Trying to install on my system which runs a derivative of Ubuntu 22.04.1 LTS, it fails to install and gives a alert popup:

> An error occurred
> Could not locate runtime 'runtime/io.elementary.Platform/x86_64/6.1' in any registered modules

**Comment by eliottthomas99** [comment]
Same for me, did you find a solution ? The distribution I use is Zorin OS

**Comment by amka** [comment]
Hey guys! Did you try to install it from Flathub or not? Version 1.2.0 has no links to this Elementary runtime. It would be awesome if you could check it.

**Comment by rayrrr** [comment]
@amka given that I titled this issue "Flatpak install failed" I'm rather confident that was the install method I attempted. :smile: Just checked again and now IT WORKS! Thanks!

**Comment by amka** [comment]
Ah, not Flatpak but **Flathub** :) I mean the source of the app. Anyway, I'm glad your issue was resolved!
