### ISSUE TITLE
Flatpak Frog downloads from tessdata instead of tessdata_best

### ISSUE THREAD

**Issue by Albnu14** [TenderOwl/Frog#82]
Hi, 
I'm trying to ocr an arabic image, but frog couldn't read anything from the image, when i replaced the ara.tessdata from the frog flatpak directory with the one i downloaded from tessdata_best, frog managed to ocr tge image with great success. 

Even using tessdata_fast had a very good success. 

Please make tessdata_best the default

**Comment by amka** [comment]
As you can see in the code we're trying to get the `_best` model by default and if an error happens we switch to the `base` model.
https://github.com/TenderOwl/Frog/blob/5608ab34547fc639dd97a31cab018a9ea0a18c35/frog/language_manager.py#L201

**Comment by Albnu14** [comment]
Great, i will close the issue then.
