### ISSUE TITLE
Support for Ubuntu

### ISSUE THREAD

**Issue by soumyaDghosh** [TenderOwl/Frog#84]
Please explain how should I compile this app in ubuntu, with all the necessary dependencies. Or if you're planning to release a deb. We have a project called [Pacstall](pacstall.dev). We can serve your deb via there. Or, we'll compile the app from source and serve it in our Pacstall.

**Comment by werdahias** [comment]
related to #108 . I have some basic packaging lying around, once debian bookworm is released I might package it.

**Comment by soumyaDghosh** [comment]
I have tried to make a snap for it. But, it fails with some gtk4 issues, can you help me, if I give you the logs?
