### ISSUE TITLE
Search languages

### ISSUE THREAD

**Issue by gregorni** [TenderOwl/Frog#88]
It's sometimes hard to find a specific language because the list is quite long. It would be nice to be able to search for a language.

**Comment by amka** [comment]
@gregorni  What about this?

[Запись экрана от 2023-03-19 01-14-31.webm](https://user-images.githubusercontent.com/519146/226143188-0145a41a-32d4-4e13-8123-12c6c6cfa896.webm)

**Comment by gregorni** [comment]
I like it!

**Comment by amka** [comment]
Awesome, will be available soon in 1.3 :)
